- name: apt update/upgrade
  become: yes
  apt:
    update_cache: yes
    upgrade: safe
- name: apt install common packages
  become: yes
  apt:
    name: "{{ apt.packages }}"
    state: latest
- name: create symlink of dotfiles dir
  file:
    src: "{{ dirs.dotfiles.src }}"
    dest: "{{ global.dirs.dotfiles }}"
    state: link
- name: create symlink of each dotfiles
  file:
    src: "{{ global.dirs.dotfiles }}/{{ item }}"
    dest: "{{ global.dirs.home }}/{{ item }}"
    state: link
  with_items: "{{ dotfiles }}"
- name: git clone autojump
  git:
    repo: https://github.com/joelthelion/autojump.git
    dest: "{{ dirs.autojump }}"
    depth: 1
- name: install autojump
  shell: ./install.py
  args:
    chdir: "{{ dirs.autojump }}"
