- name: apt update/upgrade
  become: yes
  apt:
    update_cache: yes
    upgrade: safe
- name: apt install common packages
  become: yes
  apt:
    name: "{{ apt.packages }}"
    state: latest
- name: create symlink of dotfiles dir
  file:
    src: "{{ dirs.dotfiles.src }}"
    dest: "{{ dirs.dotfiles.dest }}"
    state: link
- name: git clone autojump
  git:
    repo: https://github.com/joelthelion/autojump.git
    dest: "{{ dirs.autojump }}"
    depth: 1
- name: install autojump
  shell: ./install.py
  args:
    chdir: "{{ dirs.autojump }}"
- name: generate ssh key pair
  shell: |
    ssh-keygen -q -t ed25519 -N "" -C "vagrant@${HOST}" -f ~/.ssh/id_ed25519
    curl --user "epaew" -H "Accept: application/vnd.github.v3+json" \
      -X POST -d "{\"title\":\"$(uname -nr)\", \"key\":\"$(cat ~/.ssh/id_ed25519.pub)\"}" \
      https://api.github.com/user/keys
  args:
    creates: ~/.ssh/id_ed25519
    stdin: "{{ secrets.github }}"
