- name: apt install qmk required packages
  become: yes
  apt:
    name: "{{ apt.packages }}"
    state: latest

- name: mkdir ~/workspace
  file:
    path: "{{ dirs.workspace }}"
    state: directory
- name: git checkouts
  git:
    repo: "{{ item.url }}"
    dest: "{{ item.dest }}"
    depth: "{{ item.depth }}"
  with_items:
    - "{{ repos }}"
