- name: apt install qmk required packages
  become: true
  apt:
    name:
      - avr-libc
      - binutils-avr
      - binutils-arm-none-eabi
      - dfu-programmer
      - dfu-util
      - gcc
      - gcc-arm-none-eabi
      - gcc-avr
      - git
      - libnewlib-arm-none-eabi
      - unzip
      - zip
    state: latest
- name: mkdir workspace
  file:
    path: "{{ global.dirs.home }}/workspace"
    state: directory
