- name: apt install qmk required packages
  become: true
  apt:
    name:
      - avr-libc
      - binutils-avr
      - binutils-arm-none-eabi
      - build-essential
      - dfu-programmer
      - dfu-util
      - gcc
      - gcc-arm-none-eabi
      - gcc-avr
      - libnewlib-arm-none-eabi
      - unzip
      - wget
      - zip
    state: latest
