apt:
  packages:
    - neovim
    #- pyenv
    - python3-pip
dirs:
  dein_sub: "{{ global.dirs.home }}/.cache/dein/repos/github.com/Shougo"
  dein: "{{ global.dirs.home }}/.cache/dein/repos/github.com/Shougo/dein.vim"
  # known bug:  it causes recursive loop error
  #dein: "{{ dirs.dein_sub }}/dein"
  config:
    src: "{{ global.dirs.dotfiles }}/config/nvim"
    dest_sub: "{{ global.dirs.home }}/.config"
    dest: "{{ global.dirs.home }}/.config/nvim"
