- name: apt install rails required packages
  become: yes
  apt:
    name: "{{ apt.packages }}"
    state: latest

- name: mkdir ~/workspace
  file:
    path: "{{ global.dirs.workspace }}"
    state: directory
- name: git checkouts
  git:
    repo: "{{ item.url }}"
    dest: "{{ item.dest }}"
    depth: "{{ item.depth }}"
  with_items:
    - "{{ repos }}"
- name: bundle install
  shell: |
    bundle install --path vendor/bundle
  args:
    chdir: "{{ item.dest }}"
  with_items:
    - "{{ repos }}"
- name: install heroku cli via snap
  become: yes
  shell: |
    snap install heroku --classic
    rehash
    heroku plugins:install heroku-redis
