- name: apt install tmux
  become: yes
  apt:
    name:
      - tmux
    state: latest
- name: mkdir ~/.tmux/plugins
  file:
    path: "{{ dirs.tpm_sub }}"
    state: directory
- name: git clone tpm
  git:
    repo: https://github.com/tmux-plugins/tpm.git
    dest: "{{ dirs.tpm }}"
    depth: 1
- name: create symlink of tmux.conf
  file:
    src: "{{ dirs.config.src }}"
    dest: "{{ dirs.config.dest }}"
    state: link
# TODO: it's not working.
#- name: install tmux plugins
#  shell: "TMUX_PLUGIN_MANAGER_PATH={{ dirs.tpm_sub }} /bin/bash {{ dirs.tpm }}/scripts/install_plugins.sh"
#  args:
#    executable: /usr/bin/tmux
