- name: apt install xserver-xorg
  become: yes
  apt:
    name:
    - xserver-xorg
    state: latest
    update_cache: yes
- name: apt install xubuntu-desktop
  become: yes
  apt:
    name:
    - xubuntu-desktop
    state: latest
    update_cache: yes
- name: apt install extra GUI utilities
  become: yes
  apt:
    name: "{{ apt.packages }}"
    state: latest
    update_cache: yes
- name: apt autoremove
  become: yes
  apt:
    autoremove: yes
- name: create symlink of each dotfiles
  file:
    src: "{{ global.dirs.dotfiles }}/{{ item }}"
    dest: "{{ global.dirs.home }}/{{ item }}"
    state: link
  with_items: "{{ dotfiles }}"
