apt:
  packages:
    - build-essential
    - git
    - make
    - rake
    - tig
    - wget
    - xsel
    - xserver-xorg
    - xubuntu-desktop
dirs:
  autojump: "{{ global.dirs.home }}/autojump"
  dotfiles:
    src: /Vagrant/dotfiles
dotfiles:
  - .gitconfig
  - .tigrc
